{
 "title": "ASP.NET Core - controller summary (Prometheus)",
 "description": "Basic measurements of request handling using data from prometheus-net middleware",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Instances",
    "query": "label_values(http_requests_received_total, instance)"
   },
   {
    "name": "controllers",
    "label": "Controllers",
    "query": "label_values(http_requests_received_total{instance =~ \"$instances\"}, controller)"
   }
  ]
 },
 "panels": [
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum)/sum(http_requests_received_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{code!=\"200\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90-percentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) \n(rate(http_request_duration_seconds_bucket[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Default",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests received by controller",
     "type": "graph",
     "description": "Counts all requests, both successful and failed",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m])) by (controller)",
       "legendFormat": "{{controller}}"
      },
      {
       "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\"}[3m]))",
       "legendFormat": "(None)"
      }
     ]
    },
    {
     "title": "Total req/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\"}[3m]))"
      }
     ]
    },
    {
     "title": "In progress (global)",
     "type": "stat",
     "description": "Across ALL controllers globally!",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_in_progress{instance =~ \"$instances\"})"
      }
     ]
    },
    {
     "title": "Request duration (controller-handled requests only)",
     "type": "heatmap",
     "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 6 },
     "targets": [
      {
       "expr": "sum(increase(http_request_duration_seconds_bucket{instance =~ \"$instances\", controller =~ \"$controllers\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Error rate by controller",
     "type": "graph",
     "description": "4xx and 5xx status codes",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
       "legendFormat": "{{controller}}"
      },
      {
       "expr": "sum(rate(http_requests_received_total{instance =~ \"$instances\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[3m])) by (controller)",
       "legendFormat": "(None)"
      }
     ]
    }
   ]
  }
 ]
}